name: elea_chat
description: "Elea chat app."
publish_to: 'none'
version: 0.1.2+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  badges: ^3.1.2
  cloud_firestore: ^4.17.3
  emoji_picker_flutter: ^2.2.0
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.6
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  image: ^4.2.0
  image_picker: ^1.1.2
  intl: ^0.18.1
  multi_select_flutter: ^4.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  timeago: ^3.6.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/notification_sound.wav
    - assets/sounds/notification_sound2.wav

