name: Build and Distribute

on:
  push:
    branches:
      - test
      - live

jobs:
  build:
    runs-on: macos-latest

    environment: ${{ github.ref == 'refs/heads/live' && 'live' || 'test' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5'

    - name: Decrypt and install provisioning profile
      run: |
        echo "${{ secrets.IOS_PROVISIONING_PROFILE }}" | base64 --decode > provisioning_profile.mobileprovision
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp provisioning_profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

    - name: Decrypt and install certificate
      run: |
        echo "${{ secrets.IOS_CERTIFICATE }}" | base64 --decode > ios_certificate.p12
        security create-keychain -p "" build.keychain
        security import ios_certificate.p12 -t agg -k ~/Library/Keychains/build.keychain -P "${{ secrets.IOS_CERTIFICATE_PASSWORD }}" -A
        security list-keychain -d user -s ~/Library/Keychains/build.keychain
        security unlock-keychain -p "" ~/Library/Keychains/build.keychain
        security set-key-partition-list -S apple-tool:,apple: -s -k "" ~/Library/Keychains/build.keychain

    - name: Install CocoaPods dependencies
      run: |
        cd ios
        pod install

    - name: Build iOS app
      run: flutter build ios --release --no-codesign

    - name: Archive iOS app
      run: |
        xcodebuild -workspace ios/Runner.xcworkspace \
        -scheme Runner \
        -sdk iphoneos \
        -configuration Release \
        -archivePath $PWD/build/Runner.xcarchive \
        archive

    - name: Export iOS app
      run: |
        xcodebuild -exportArchive \
        -archivePath $PWD/build/Runner.xcarchive \
        -exportOptionsPlist ios/Runner/ExportOptions.plist \
        -exportPath $PWD/build