name: Build and Distribute

on:
  push:
    branches:
      - test
      - live

jobs:
  build:
    runs-on: macos-latest

    env:
      IOS_CERTIFICATE: ${{ secrets.IOS_CERTIFICATE }}
      IOS_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
      IOS_PROVISIONING_PROFILE: ${{ secrets.IOS_PROVISIONING_PROFILE }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Decrypt and install provisioning profile
      run: |
        echo $IOS_PROVISIONING_PROFILE | base64 --decode > provisioning_profile.mobileprovision
        cat provisioning_profile.mobileprovision
